micronaut:
  application:
    name: google-drive-upload

  server:
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:static"

oci-google-drive:
  application:
    name: "OCI Google Drive Uploader"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
      - "https://www.googleapis.com/auth/gmail.send"
