micronaut:
  application:
    name: check-ins

  server:
    cors:
      enabled: true
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:public"

check-ins:
  application:
    name: "OCI Check-ins"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
      - "https://www.googleapis.com/auth/gmail.send"
