micronaut:
  application:
    name: check-ins

  server:
    cors:
      enabled: true
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:public"

check-ins:
  application:
    name: "OCI Check-ins"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
      - "https://www.googleapis.com/auth/gmail.send"

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update