micronaut:
  application:
    name: check-ins

  server:
    cors:
      enabled: true
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:public"

check-ins:
  application:
    name: "OCI Check-ins"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
      - "https://www.googleapis.com/auth/gmail.send"

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql:///${DB_NAME}?cloudSqlInstance= ${DB_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory`}
    driverClassName: org.postgresql.Driver
    username: ${ DB_USERNAME }
    password: ${ DB_PASSWORD }
    schema-generate: CREATE
    dialect: POSTGRES

micronaut:
  security:
    enabled: true
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${ OAUTH_CLIENT_ID }
          client-secret: ${ OAUTH_CLIENT_SECRET }
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      -
        pattern: /**
        http-method: GET
        access:
          - isAnonymous()
    session:
      enabled: true 
      login-success-target-url: '/'
      unauthorized-target-url: '/unauthorized'
      forbidden-target-url: '/forbidden'
      