name: Gradle Build - Feature / Bug
on:
  push:
    branches:
      - 'feature-**/*'
      - 'bugfix-**/*'
      - 'chore-**/*'
      - 'doc-**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do SonarQube checks
        run: ./gradlew sonarqube -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONARQUBE_TOKEN
        env:
          SONAR_PROJECT_KEY: oci-checkins
          SONAR_URL: https://sonarqube.cloudops.objectcomputing.com
      - name: force build failure if SonarQube problems
        run: curl -u "$SONARQUBE_TOKEN:" https://sonarqube.cloudops.objectcomputing.com/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY > result.json
          - cat result.json
          - if [[ $(jq -r '.projectStatus.status' result.json) = ERROR ]] ; then exit 1;fi
        env:
            SONAR_PROJECT_KEY: oci-checkins