name: Gradle Build - Feature / Bug
on:
  push:
    branches:
      - 'feature-**/*'
      - 'bugfix-**/*'
      - 'chore-**/*'
      - 'doc-**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle package
        run: ./gradlew assemble
      - name: Do SonarQube checks
        run: ./gradlew check jacocoTestReport sonarqube -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_URL -Dsonar.login=$TOKEN
        env:
          SONAR_PROJECT_KEY: oci-labs_oci-checkins
          SONAR_ORG: oci-labs
          SONAR_URL: https://sonarcloud.io
          TOKEN: 76d54e72c4fbab6a5d7928cc95e2e9248986b1c5