# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle package
#       run: ./gradlew assembleServerAndClient
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: 7eaa31ede1a044600ae8bc7bda1bbe48157d38a1
        SONAR_TOKEN: b519068046bdfc31bc0cc924fd091d637bb7d7ac
