name: Gradle Build & Deploy GCE
on:
  push:
    branches:
      - 'feature-38/deploy-gce'
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: checkins-develop
  GITHUB_SHA: ${{ github.sha }}
  GCE_INSTANCE_ZONE: us-central1-a
jobs:
  build_deploy_gce_gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
      - name: Auth Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Build the Docker image
        run: |-
          cd server
          docker build --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" .
      - name: Push the Docker image to Google Container Registry
        run: |-
          cd server
          docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      - name: Deploy image to Compute Engine Instance
        run: |-
          gcloud compute instances update-container $SERVICE_NAME \
            --zone $GCE_INSTANCE_ZONE \
            --container-image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --container-env CLOUD_DB_CONNECTION_NAME="${{ secrets.DEV_DB_CONNECTION_NAME }}",DB_NAME="${{ secrets.DEV_DB_NAME }}",DATASOURCES_DEFAULT_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}",DATASOURCES_DEFAULT_USERNAME="${{ secrets.DEV_DB_USERNAME }}",OAUTH_CLIENT_ID="${{ secrets.OAUTH_CLIENT_ID }}",OAUTH_CLIENT_SECRET="${{ secrets.OAUTH_CLIENT_SECRET }},MICRONAUT_SERVER_PORT=80"

      - name: Start the docker image with ENV
        run: |-
          gcloud compute ssh $SERVICE_NAME --zone $GCE_INSTANCE_ZONE --command "docker run -d gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
